Provide support for cache_from and cache_to fields
containers/podman-compose pull request #1092
Opened 2024-12-28 19:51 UTC by flixman

Currently the fields cache_from and cache_to on the buildare ignored. This PR provides support for them in the build block, just by propagating them to the call to podman.

2024-12-29 22:57 UTC, p12tic requested changes
Thanks for the PR. It looks good in principle.

What's missing:
 - unit tests. I did some refactoring and added unit tests for image building functionality in https://github.com/containers/podman-compose/pull/1094
 - release note. Please see newsfragments/README.txt file

Also, podman build [documentation](https://docs.podman.io/en/v5.3.0/markdown/podman-build.1.html#cache-from-image) says that cache-from is ignored unless `--layers` is specified. I suppose this PR won't do what user expects as is, what am I missing?

2024-12-29 22:58 UTC, p12tic commented
Also, please rebase instead of merging main, thanks!

2024-12-30 07:13 UTC, flixman commented
@p12tic About the --layers flag: I also saw the documentation, but I made a couple of tests and caches are used regardless on --layers being set or not. I have just reported this to [podman](https://github.com/containers/podman/issues/24916), because looks like might be an error on the documentation.

2024-12-30 07:16 UTC, flixman commented
@p12tic about the branch update (merging vs rebasing): Can't the "update with merge" be disabled on the GH UI? I just clicked on "update" and it did a merge. Now I have seen I had the option to "update with rebase", but if that is not valid... maybe should just not appear at all?

2024-12-30 07:17 UTC, p12tic commented
> Can't the "update with merge" be disabled on the GH UI? I just clicked on "update" and it did a merge.

Unfortunately github UI does not support this. They have different options for actual merging, but for the update button - no.

2025-01-03 15:14 UTC, p12tic commented
Still needs a release note.

> - release note. Please see newsfragments/README.txt file

2025-01-05 10:34 UTC, p12tic approved these changes

2025-01-05 10:37 UTC, flixman commented
@p12tic I have seen there were changes to main, and I have rebased my branch on top of it. Do you need to approve again?

2025-01-05 11:11 UTC, p12tic commented
I also combined the fixup commits into the feature commit, so that a commit groups one logical change. See https://metal-k8s.readthedocs.io/en/2.4.1/developer/best_practices/commit.html for an example of commit best practices. Podman-compose should probably have a link to similar page in PR template.

2025-01-05 11:11 UTC, p12tic approved these changes

2025-01-05 11:11 UTC, merged