Support podman's external rootfs management
containers/podman-compose pull request #737
Opened 2023-07-29 08:58 UTC by ftyghome

The podman-run command supports external rootfs management by using the --rootfs flag ([documentation](https://docs.podman.io/en/latest/markdown/podman-run.1.html#rootfs)).
By specifying the --rootfs flag, the first parameter of podman-run will be the path of container's rootfs, instead of the specification of image. This patch makes the compose file parser able to recognize the "rootfs" field, and produce the correct args for podman-run command.

2024-03-09 00:26 UTC, p12tic commented on podman_compose.py
> +    rootfs = cnt.get("rootfs", None)
Is this part of the compose spec? If not, podman-specific keys should be prefixed (e.g. podman.io-rootfs). Also we should have a documentation for such additions somewhere.

2024-03-09 00:28 UTC, p12tic requested changes
Thanks for the PR. It looks good in principle. 

Unit tests are needed. `pytests/test_container_to_args.py` already tests some of the ways to call `container_to_args`.

2024-03-16 08:20 UTC, ftyghome commented
Hi! 
I have moved podman-specific keys under the "x-podman" field, as the "uidmap" and "gidmap" did.
Unit tests are added, and documents about the extensions are mentioned in the docs/Extensions.md.
Thanks for reviewing:)

2024-03-27 22:43 UTC, p12tic approved these changes
Looks great!

I've now realized that there are two ways to supply podman-specific config keys. This will be addressed in the future in a separate PR.

2024-04-28 14:42 UTC, p12tic commented
Rebased.

2024-04-28 15:04 UTC, merged

2024-04-28 15:26 UTC, p12tic commented
@ftyghome FYI I updated location of the rootfs config in https://github.com/containers/podman-compose/pull/917.