Handle sysctls maps
containers/podman-compose pull request #764
Opened 2023-09-09 06:50 UTC by lemmi

- Add support to handle sysctls maps.
- Directly raise an error if sysctls is neither an array nor map instead of letting podman fail with an unhelpful message.

Support for sysctls arrays was added in #261.

Fixes #754: sysctls only works with arrays, not maps

2024-03-08 22:46 UTC, p12tic requested changes
Looks good, thanks for the PR.

Could unit tests be added? There's an example in `pytests/test_container_to_args.py`.

2024-03-09 10:12 UTC, lemmi commented
When I ran the tests with `python -m unittest pytests/test_container_to_args.py`, they didn't seem to actually run and I was getting a bunch of warnings like 
```
/usr/lib/python3.12/unittest/case.py:589: RuntimeWarning: coroutine 'TestContainerToArgs.test_minimal' was never awaited
...
```
I switched the test class over to [`unittest.IsolatedAsyncioTestCase`](https://docs.python.org/3/library/unittest.html#unittest.IsolatedAsyncioTestCase) and with that the tests actually ran and failed when something was wrong.

I'm not very familiar with python or its tooling, so there might be a better solution.

If you want me to move the `sysctl` test somewhere else or have suggestions for more tests, let me know.

2024-03-09 10:26 UTC, p12tic commented on pytests/test_container_to_args.py
> +class TestContainerToArgs(unittest.IsolatedAsyncioTestCase):
This is great discovery, thanks.

2024-03-09 10:34 UTC, lemmi commented on pytests/test_container_to_args.py
> +        self.assertEqual(
Yeah makes sense. I split it in two test cases and made the assertion explicit.

2024-03-09 10:45 UTC, p12tic commented
Rebased and reordered commits.

2024-03-09 10:45 UTC, p12tic approved these changes
Looks great.

2024-03-09 10:47 UTC, merged