Fix environment variable precedents
containers/podman-compose pull request #771
Opened 2023-09-13 13:35 UTC by wgnathanael

Allow environment variables set in the host os to override the value of a variable defined in a .env file.
This is consistent with docker's environment variable precedence. Per https://docs.docker.com/compose/environment-variables/envvars-precedence/#advanced-example

2024-03-08 21:39 UTC, p12tic requested changes
Need proper test for this.

2024-03-21 14:48 UTC, wgnathanael commented
I'd love to submit some tests but I can't even find existing tests that test the env/env-file features as is. Is there one I can use a template someplace?

2024-06-18 18:48 UTC, charliemirabile commented
@p12tic bump on this issue. I (and presumably @wgnathanael) would love to get this merged as I am currently relying on it in my own fork to be able to use podman-compose in production, but it needs tests. Happy to contribute some, but as @wgnathanael says, there doesn't seem to be any infrastructure in place for testing the existing environment variable code. Do you have any sense of how this could be tested in a reasonably straightforward way?

2024-06-22 16:52 UTC, p12tic commented
Thanks for the bump, I somehow missed @wgnathanael comment. If there is no testing infrastructure for a feature, it's more of a responsibility of the maintainer to define one instead of infrequent contributors. I will merge this PR as is.

2024-06-22 16:55 UTC, p12tic commented
Rebased and fixed merge conflict.

2024-06-22 16:58 UTC, p12tic approved these changes

2024-06-22 17:00 UTC, merged