Lint fixes and enhancements
containers/podman-compose pull request #779
Opened 2023-09-21 22:10 UTC by jbaptperez

A couple of modifications:

1. Fixes lint issues (flake8 and pylint),
2. Fixes typos and enhances text in README.md,
3. Formats Markdown in README.md.

2024-03-08 22:13 UTC, p12tic requested changes
Thanks for the PR.

In the documentation, please keep line length to around 100 chars or less.
 
The unit tests have migrated from pylint to unittest, so these changes are probably no longer relevant.

I understand a lot of time have passed, so you probably won't have time to go back to the PR. Maybe someone else can use the review to help extract useful stuff from the PR.

2024-03-17 18:39 UTC, jbaptperez commented
@p12tic

> Thanks for the PR.
> 
> In the documentation, please keep line length to around 100 chars or less.

Done.

> The unit tests have migrated from pylint to unittest, so these changes are probably no longer relevant.
> 
> I understand a lot of time have passed, so you probably won't have time to go back to the PR. Maybe someone else can use the review to help extract useful stuff from the PR.

I removed outdated fixes, rebased my branch on `main` and updated the PR.

However, the pytest to unitest and ruff migrations look not to be completed and I think `README.md` and `CONTRIBUTING.md` (or even `setup.py`) have to be updated accordingly.

2024-03-27 22:35 UTC, p12tic commented
> However, the pytest to unitest and ruff migrations look not to be completed and I think README.md and CONTRIBUTING.md (or even setup.py) have to be updated accordingly.

Thanks, indeed..

2024-03-27 22:36 UTC, p12tic approved these changes

2024-03-27 22:36 UTC, merged