Support all healthcheck options in Compose
containers/podman-compose pull request #780
Opened 2023-09-24 09:53 UTC by recursiveribbons

- Added start_interval to the healthcheck block parser
- Changed the healthcheck flags to the normalized podman flags

2024-03-08 22:09 UTC, p12tic requested changes
Thanks for the PR. It looks good.

Please add unit tests. See e.g. pytests/test_container_to_args.py for an example.

2024-03-09 15:30 UTC, recursiveribbons commented
(rebased branch onto main and force pushed)

2024-03-11 22:43 UTC, recursiveribbons commented
I'm not sure how to fix the unit test, as `--health-startup-interval` does not exist in podman 4.3.1, which is the version shipped with Debian Bookworm (latest version is 4.9.3)

2024-03-11 23:00 UTC, recursiveribbons commented
Do you actually want me to commit the entire formatted podman_compose.py file or just let the test fail?

also the pre-commit checks wants me to format 10 files so I'm not sure if I should

2024-10-26 13:23 UTC, d0b3rm4n commented on podman_compose.py
> +                podman_args.extend(["--health-cmd", "/bin/sh -c " + cmd_q])
I don't think in `CMD` case this should be executed with ` /bin/sh` prevents cases from working where there is no  `/bin/sh` in the image like minimal images for Rust applications. I don't have docker to verify, but from the documentation, my understanding is that this is ran without shell.

2026-05-04 20:34 UTC, p12tic commented
Merged via https://github.com/containers/podman-compose/pull/1271

2026-05-04 20:34 UTC, closed without merging