Fix #782: add support for `http-proxy` option of podman
containers/podman-compose pull request #783
Opened 2023-09-24 23:43 UTC by ChuJiani

2023-10-11 05:43 UTC, JAORMX approved these changes

2023-10-15 03:45 UTC, NerdToMars approved these changes

2024-03-08 22:07 UTC, p12tic requested changes
Thanks for the PR.

Please add unit tests. See e.g. pytests/test_container_to_args.py for an example.

2024-03-09 11:58 UTC, ChuJiani commented
Unit test added in `pytests/test_container_to_args.py`.

Are there any need to place this option into or behind [net_args](https://github.com/containers/podman-compose/blob/121b5f6ea1b6bc1f8ea4ddf4ebc7ff809d5b876e/podman_compose.py#L926)?

2024-03-09 15:38 UTC, p12tic commented
> Also: Do I need to place this option into or behind net args

There's stuff like `--dns` ten lines below your change, so I think it doesn't matter for now.

The PR looks good. Could you rebase on top of `main` instead of merging? This whole PR can be a single commit.

2024-03-09 15:38 UTC, p12tic commented on podman_compose.py
> +    if cnt.get("http_proxy", None) == False:
This should be `is False`.

2024-03-09 16:06 UTC, ChuJiani commented
Sure! I will figure it out.

2024-03-09 17:17 UTC, ChuJiani commented
Sorry I messed things up. It took me some time to rebase/reset. But It should work fine now.

By the way, it seems that the commit just before mine, which is about `pid`, does not pass the unit test.

2024-03-09 21:27 UTC, merged

2024-03-09 21:27 UTC, p12tic commented
Thanks, looks great!