Remove implemented commands from Missing Commands
containers/podman-compose pull request #861
Opened 2024-03-01 21:20 UTC by aripollak

2024-03-08 18:52 UTC, p12tic commented
@aripollak Please add signed-off-by line as required by the DCO policy. See https://github.com/containers/podman-compose/pull/861/checks?check_run_id=22449595686

2024-03-08 22:02 UTC, p12tic requested changes
Needs signed-off-by line in commit message.

2024-03-09 19:20 UTC, aripollak commented
> Needs signed-off-by line in commit message.

@p12tic done.

2024-03-09 21:26 UTC, p12tic approved these changes

2024-03-09 21:26 UTC, merged