support volume mapping into the home of a container
containers/podman-compose pull request #885
Opened 2024-03-09 09:59 UTC by maurerle

It is supported in docker compose to have a volume mapping like `/foo:~/data` which should also be supported by podman compose.

This PR allows using this too.

2024-03-09 10:28 UTC, p12tic commented
@maurerle Thanks for the PR. Is tilde volume mapping specified in the compose spec? I couldn't find it.

2024-03-09 10:31 UTC, p12tic requested changes
Thanks for the PR, it looks good.

This will need unit tests for the `parse_short_mount()` function. But before spending time on these let's wait for me to understand what part of compose spec or undocumented docker compose behavior we are dealing with.

2024-03-09 11:41 UTC, maurerle commented
I think that this is not documented here:
https://github.com/compose-spec/compose-spec/blob/master/07-volumes.md

It just says that the destination can be a part inside the docker container - so any valid unix path would be fine, including those starting with a tilde `~`
If it does not start with an absolute path - say plain `data`, `docker compose` says `invalid mount path: 'data' mount path must be absolute` - so ~ is interpreted as a valid absolute path..

2024-03-09 15:40 UTC, p12tic commented
OK, replicating undocumented behavior is fine. I was just concerned that this is documented in the spec but I can't find it.

2024-03-12 13:33 UTC, maurerle commented
I don't know what happened but somehow this does not work with docker compose either.. `~/data:rw': invalid mount config for type "bind": invalid mount path: '~/data' mount path must be absolute`
Weird - problem some wrong assumptions i had when testing before..
Sorry for that.

2024-03-12 13:33 UTC, closed without merging