Fix, use "service.build.ulimits" when it is present instead of "service.ulimits"
containers/podman-compose pull request #906
Opened 2024-04-08 07:16 UTC by camspiers

https://github.com/compose-spec/compose-spec/pull/433

2024-04-08 20:15 UTC, p12tic requested changes
Looks good in principle, but needs unit tests.

2024-04-09 02:45 UTC, camspiers commented
Hey @p12tic thanks for reviewing the PR. I have updated with unit tests, but I am not 100% on what I have done.

At the moment I am testing both that the ulimits are passed correctly to the build command, and that the ulimits are applied during the build. However I could solely test that the right arguments are passed to the build command using the dry-run flag and remove the actual execution of the ulimit command in the build.

2024-04-17 16:42 UTC, p12tic approved these changes

2024-04-17 16:46 UTC, p12tic commented
Rebased and shortened commit message to max 72 chars allowed by git.

2024-04-17 16:48 UTC, merged