Fixes #908: Add support for multi-line environment files
containers/podman-compose pull request #909
Opened 2024-04-08 21:52 UTC by hedayat

TBH, I don't find the part of compose spec which specifies this. Actually, it might not be according to the spec. However, this is what docker compose supports... !

2024-04-17 16:40 UTC, p12tic commented on podman_compose.py
> +        dotenv_dict = {}
Needs a test. See pytests directory

2024-04-17 16:40 UTC, p12tic requested changes
Looks good, but needs tests

2024-05-28 23:57 UTC, p12tic commented
This PR has been merged via https://github.com/containers/podman-compose/pull/949.

2024-05-28 23:57 UTC, closed without merging

2024-06-03 09:01 UTC, mokibit commented
Tests added in https://github.com/containers/podman-compose/pull/949.