Add supoort for enabling GPU access
containers/podman-compose pull request #920
Opened 2024-04-30 09:25 UTC by mokeyish

closes #919

2024-05-01 18:09 UTC, p12tic requested changes
Looks good, thanks.

Could you add unit tests? There's a bunch already in pytests/test_container_to_args.py. It should be easy to extend the test suite for the GPU options. The existing tests test `container_to_args()` which I think is appropriate level of detail for the additional GPU tests.

2024-05-06 05:56 UTC, mokeyish commented
@p12tic  I looked at the existing unit tests and it was a bit difficult to understand. It seems to be output after execution. But Github Actions does not have a GPU and cannot be tested.

2024-05-06 11:17 UTC, p12tic commented
@mokeyish Tests in pytests/test_container_to_args.py don't actually run any containers.

The test structure is as follows:
 - create compose definition in parsed form (i.e. python dicts, lists, etc. are used)
 - run it through container_to_args function
 - the result is arguments which would be otherwise sent to podman. The test simply compares them to what's expected and does not run podman.
 
With such tests any feature of podman-compose can be tested without any requirements from hardware.

2024-05-06 11:18 UTC, p12tic commented
So in GPU tests I would expect tests that check whether correct GPU-related options are added to podman_args.

2024-05-07 15:29 UTC, p12tic commented on pytests/test_container_to_args.py
> +    async def test_gpu(self):
This test is actually 4 tests. Could you split it. It's ok if the preamble

```
        c = create_compose_mock()

        cnt = get_minimal_container()
        cnt["command"] = ["nvidia-smi"]
        cnt["deploy"] = {"resources": {"reservations": {"devices": [{}]}}}
```

repeats in each test.

2024-05-19 08:12 UTC, merged